name: Java CI with Maven

on:
  pull_request:
    branches: [ main ] # Change to 'master' if your default branch is 'master'
  push:
    branches: [ main ] # Change to 'master' if your default branch is 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run unit tests
        run: mvn test --file pom.xml
